version: '3.3'

networks:
  monitoring:

services:

  pihole_exporter:
    image: remiflandrois/pihole-exporter:latest
    environment:
        - PIHOLE_HOSTNAME=XXXXX
        - PIHOLE_PASSWORD=XXXXX
        - INTERVAL=5s
        - PORT=9617
    ports:
        - 9617:9617
    networks:
        - monitoring
    restart: always


